### ISSUE TITLE
AWS - EC2 Exposures

### ISSUE THREAD

**Issue by poojacmlab** [expand-network/sdk-nodejs#29]
1. Jenkins Ports
2. Exposing the API key generation server to the Internet allows bypassing the load balancer and any controls applied to that

**Comment by varun24143** [comment]
The following security measures have been reviewed and implemented:

1. We have reviewed and eliminated the unnecessary exposures(aka ports0 and also eliminated the public IP addresses from systems that should not be publicly accessible, thus minimised the attack surface.
2. Our current Jenkins deployment is manual, and access to the instance is restricted to authorized users through a designated port. As a result, there is no public accessibility to Jenkins.
3. Scrutinized all security groups to ensure they permit traffic only from authorized sources, and not relying on the default security groups created.

**Comment by varun24143** [comment]
We utilize GitHub Actions for deployment across various environments. GitHub Actions automates workflow execution based on predefined events, and the workflow itself is executed exclusively on our servers. Sensitive information is securely stored on these servers, ensuring that it remains confidential during GitHub Actions workflows. The workflow logs and results are conveniently accessible and viewable directly on GitHub.
